apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-fast-api-deployment
  labels:
    app: ms-fast-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-fast-api
  template:
    metadata:
      labels:
        app: ms-fast-api
    spec:
      containers:
      - name: ms-fast-api-container
        image: lucatocampos/ms-fast-api:latest # Substitua pelo nome da sua imagem no registro
        ports:
        - containerPort: 8080
        env:
        - name: ENVIRONMENT_VARIABLE_NAME
          value: "value" # Adicione suas variáveis de ambiente conforme necessário
