apiVersion: v1
kind: Service
metadata:
  name: ms-fast-api-service
  namespace: ms  # Certifique-se de que este namespace existe
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  selector:
    app: ms-fast-api
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
