apiVersion: v1
kind: Service
metadata:
  name: ms-fast-api-service
  namespace: ms
spec:
  selector:
    app: ms-fast-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001  # Escolha uma porta entre 30000 e 32767
  type: NodePort
