apiVersion: v1
kind: Service
metadata:
  name: ms-fast-api-service
  namespace: ms  # Certifique-se de que este namespace existe
spec:
  selector:
    app: ms-fast-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
